spring.application.name=sisrap-backend

# Datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Pool de conexiones acotado
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

server.port=${SERVER_PORT:8080}